##
## EPITECH PROJECT, 2020
## B-DEV-500-PAR-5-1-cardgames-lucas.guyader
## File description:
## docker-compose.yml
##

version: '3'
services:
    request:
        restart: always
        build: .
        command: npm start
        ports:
            - "8080"